### ISSUE TITLE
Kick-off meeting 

### ISSUE THREAD

**Issue by Yevheniia-Rudenko** [MIT-Emerging-Talent/ET6-foundations-group-12#2]
# Kick-off Meeting Agenda  

## 1. Welcome and Introduction  
- Brief opening to set the tone for the meeting.  
- Share the goals and expected outcomes of the session.  

## 2. Project Overview  
- Discuss the project’s purpose and objectives.  
- Align on key milestones and deadlines.  

## 3. Group Name and Repository Description  
- Brainstorm ideas for the group name.  
- Agree on a description and structure for the repository.  

## 4. Task Distribution  
- List all key tasks for the project.  
- Collaboratively decide who will take on each task.  

## 5. Planning and Organization  
- Outline the initial plan of action together.  
- Decide on tools, communication methods, and workflows.  

## 6. Questions and Alignment  
- Clarify any uncertainties or open questions.  
- Ensure everyone has a shared understanding of the starting point and goals.  

## 7. Next Steps  
- Summarize agreed-upon actions.  
- Set a timeline for follow-up discussions or progress updates.

**Comment by Yevheniia-Rudenko** [comment]
# **Kick-Off Meeting Summary**  
*Project: Calculator*  
*Date: December 23, 2024*

---

## **1. Project Overview**  
**Group Name:** Calculator (Subject to discussion)  
**Project Deadline:** January 6, 2025 (All deliverables should be completed by this date)

### **Group Theme: Calculator**  
The project will focus on developing various functions as part of a calculator. Below is the list of possible functions. If you have additional ideas for functions, feel free to add them.

### **List of Possible Functions:**
1. **add:** Adds two numbers and returns the result.
2. **subtract:** Subtracts the second number from the first and returns the result.
3. **multiply:** Multiplies two numbers and returns the result.
4. **divide:** Divides the first number by the second and handles division by zero.
5. **modulus:** Calculates the remainder of dividing two numbers.
6. **power:** Calculates the first number raised to the power of the second.
7. **square:** Calculates the square of a number.
8. **square_root:** Calculates the square root of a number.
9. **factorial:** Calculates the factorial of a number.
10. **absolute_value:** Returns the absolute value of a number.
11. **calculate_average:** Calculates the average of two numbers.
12. **calculate_percentage:** Calculates what percentage the first number is of the second.
13. **find_max:** Returns the larger of two numbers.
14. **find_min:** Returns the smaller of two numbers.
15. **round_number:** Rounds a number to the nearest integer or to a specified number of decimal places.
16. **logarithm:** Calculates the logarithm of a number to a specified base (default is base 10).
17. **gcd:** Finds the greatest common divisor (GCD) of two numbers.
18. **lcm:** Finds the least common multiple (LCM) of two numbers.
19. **negate:** Changes the sign of a number (positive to negative or vice versa).
20. **convert_to_binary:** Converts a number to its binary representation.
21. **median:** Finds the median of a list of numbers.
22. **mode:** Determines the mode (most frequent value) of a set of numbers.
23. **exponentiation:** A more general exponentiation function to raise any number to any power.

---

## **2. How We Work**  
### **Collaboration Model**  
- **Asynchronous Work:** We will work asynchronously with follow-up calls every Monday afternoon (on December 30 and January 6).  
- **Communication Tools:**  
   - **GitHub:** Use GitHub to track progress via the project board.  
   - **Slack:** For daily collaboration and quick discussions.  
   - **GitHub Discussions:** For technical topics, including `.md` files and functions. Create a new discussion if one does not exist.

---

## **3. Tasks for This Week**  
- **Files in Slack:**  
   Two files are available in Slack. Each member should contribute to these files by the end of this week (Deadline: December 29). These files will help us align on group norms and will later be added to the `.md` file.
   
- **Personal Deliverables:**  
   Begin working on your individual functions. The process for personal deliverables is the same as for team tasks. Ensure you check the work steps before contributing.

- **Group Files on GitHub:**  
   There are 5 group files on GitHub. Collaboration from all members is needed. You can start working on them, and others will follow or contribute later.

---

## **4. Team Workflow and Collaboration Guidelines**  

### **Process for Starting Tasks**  
- **Create an Issue:** If you want to start a task (whether personal or part of a team `.md` file), **create an issue** in GitHub.  
- **Tracking:** Add the issue to the project board and move it through the process.  
- **Discussions:** For team deliverables, create a discussion in GitHub for input and reminders.

---

### **1. Starting Team Tasks**  
Any team member can create an issue if they identify a task that needs to be done.

### **2. Personal Deliverables**  
- **Create an Issue:** Ensure you create an issue first and add it to the project board so that everyone is aware of your progress.  
- **Code Review:**  
   - Code reviews will be done by the person who marks the task as "Ready to Review" on the project board.  
   - Ensure code quality before merging it into the main branch.

### **3. Contribution Requirements**  
Each member should complete at least **2 personal tasks** and perform **2 code reviews**.

---

## **5. Final Notes**  

### **Communication:**  
If you need help, don’t wait until Monday. We can arrange 1-on-1 sessions, text chats, or anything that works best for you.

### **Collaboration:**  
Let’s communicate openly and track progress via GitHub to stay on the same page.

---

## **6. Additional Guidelines**  

- **Branching:**  
   All development should occur in a separate branch. The branch name should reflect the task it covers. Merges to the main branch will only be possible after a review.

**Comment by Allukmon** [comment]
You all are wonderful people to work with. I appreciate your passion and commitment; it is driving me to get my hands dirty with work and not minding my skill level.

**Comment by Ridwanayinde** [comment]
Thank you all for your contributions and I am confident we will make great progress together. Cheers!

**Comment by Awaab98** [comment]
Thanks for the efforts in outlining the scope and the procedure to complete the tasks requied. Now that things are clear, lets get down to business.
